#pragma once

#include <vector>

namespace a320 {

// A significant point of Estonia's free route airspace (eAIP ENR 4.4).
struct NavFix {
  const char* ident;
  double latDeg, lonDeg;
  bool intermediate;    // FRA (I): may be used anywhere on a route
  const char* depFor;   // the airports it is a departure transition point for, space-separated
  const char* arrFor;   // ... an arrival transition point for
};

// Generated by tools/make_navdata.py (src/NavData.cpp).
const std::vector<NavFix>& estonianFixes();

}  // namespace a320
