#!/usr/bin/env python3
"""Writes core/src/NavData.cpp, the sim's waypoints, from the Estonian eAIP.

Source: ENR 4.4 "Name-code designators for significant points" of the eAIP
(https://eaip.eans.ee/<AIRAC>/html/eAIP/EE-ENR-4.4-en-GB.html). Estonia is free route airspace
(FRA): each point says whether it is an intermediate (I), entry (E), exit (X) point, or a
departure (D) / arrival (A) transition point for named airports.

    python tools/make_navdata.py                    # downloads the AIRAC below
    python tools/make_navdata.py --html ENR-4.4.html --airac 2026-10-01
"""
import argparse
import html
import re
import sys
import urllib.request

DEFAULT_AIRAC = "2026-10-01"
URL = "https://eaip.eans.ee/{airac}/html/eAIP/EE-ENR-4.4-en-GB.html"
OUT = "core/src/NavData.cpp"


def dms(text, degree_digits):
    deg = int(text[:degree_digits])
    minutes = int(text[degree_digits:degree_digits + 2])
    seconds = int(text[degree_digits + 2:degree_digits + 4])
    value = deg + minutes / 60.0 + seconds / 3600.0
    return -value if text[-1] in "SW" else value


def parse(page):
    text = html.unescape(re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", page)))
    start = text.find("1 2 3 4")
    if start < 0:
        sys.exit("ENR 4.4 table not found")
    body = text[start + len("1 2 3 4"):]
    rows = re.findall(r"([A-Z]{5}) (\d{6}[NS]) (\d{7}[EW]) (.*?)(?=[A-Z]{5} \d{6}[NS] \d{7}[EW]|$)", body)
    points = []
    for ident, lat, lon, remarks in rows:
        dep = sorted(set(a for g in re.findall(r"FRA \(D\) \(([A-Z, ]+)\)", remarks) for a in re.split(r"[, ]+", g) if a))
        arr = sorted(set(a for g in re.findall(r"FRA \(A\) \(([A-Z, ]+)\)", remarks) for a in re.split(r"[, ]+", g) if a))
        points.append((ident, dms(lat, 2), dms(lon, 3), "FRA (I)" in remarks, dep, arr))
    return points


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--airac", default=DEFAULT_AIRAC)
    ap.add_argument("--html", help="a saved ENR 4.4 page instead of downloading it")
    ap.add_argument("--out", default=OUT)
    args = ap.parse_args()
    if args.html:
        page = open(args.html, encoding="utf-8").read()
    else:
        with urllib.request.urlopen(URL.format(airac=args.airac), timeout=120) as r:
            page = r.read().decode("utf-8")
    points = parse(page)
    if len(points) < 50:
        sys.exit(f"only {len(points)} points parsed")
    lines = [
        "// Generated by tools/make_navdata.py from the Estonian eAIP ENR 4.4 (AIRAC %s). Do not edit." % args.airac,
        '#include "a320/NavData.h"',
        "",
        "namespace a320 {",
        "",
        "const std::vector<NavFix>& estonianFixes() {",
        "  static const std::vector<NavFix> kFixes = {",
    ]
    for ident, lat, lon, fra, dep, arr in points:
        lines.append('      {"%s", %.6f, %.6f, %s, "%s", "%s"},' % (ident, lat, lon, "true" if fra else "false", " ".join(dep), " ".join(arr)))
    lines += ["  };", "  return kFixes;", "}", "", "}  // namespace a320", ""]
    open(args.out, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
    print(f"{len(points)} points -> {args.out}")


if __name__ == "__main__":
    main()
